### ISSUE TITLE
Some of the podcasts aren't showing anything.

### ISSUE THREAD

**Issue by YamiYukiSenpai** [kz6fittycent/clementine#3]
[Pocketnow Weekly](https://feed.pippa.io/public/shows/5a6229bdd1a9c2d8128140d7) and [Daily](https://feed.pippa.io/public/shows/5b52e8e6c612267b5bfe8e87) aren't showing any entries when I subscribe to them.

Is there something wrong with how Clementine is reading some RSS links?

**Comment by kz6fittycent** [comment]
Have you tried using the `--edge` version? 

`snap install --edge clementine`
