### ISSUE TITLE
segfault on Ubuntu 18.04 LTS (kubuntu)

### ISSUE THREAD

**Issue by sergiusens** [kz6fittycent/clementine#5]
Recently installed on a very recently installed system
```
sergiusens@gotham:~$ clementine
Violación de segmento (`core' generado)
sergiusens@gotham:~$ which clementine
/snap/bin/clementine
sergiusens@gotham:~$ snap list clementine
Name        Version       Rev  Tracking  Publisher     Notes
clementine  1.3.1.36+git  274  stable    kz6fittycent  -
sergiusens@gotham:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
sergiusens@gotham:~$ snap version
snap    2.37.4
snapd   2.37.4
series  16
ubuntu  18.04
kernel  4.15.0-46-generic
```

**Comment by TeamLinux01** [comment]
Also have this issue on Pop!_OS 18.10 (I use fish for the shell).

user@pop-os ~> clementine
fish: “clementine” terminated by signal SIGSEGV (Address boundary error)

user@pop-os ~> which clementine
/snap/bin/clementine

user@pop-os ~> snap list clementine
Name        Version       Rev  Tracking  Publisher     Notes
clementine  1.3.1.36+git  274  stable    kz6fittycent  -

user@pop-os ~> cat /etc/os-release
NAME="Pop!_OS"
VERSION="18.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.10"
VERSION_ID="18.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic

user@pop-os ~> snap version
snap    2.38+18.10
snapd   2.38+18.10
series  16
ubuntu  18.10
kernel  4.18.0-17-generic

**Comment by kz6fittycent** [comment]
Do you mind running `snap run clementine` and sharing the output? Also, there was a recent update to the snap and you can try running the `--edge` channel.

**Comment by TeamLinux01** [comment]
user@galagopro ~> snap run clementine 
fish: “snap run clementine” terminated by signal SIGSEGV (Address boundary error)

Running snap refresh clementine --edge did fix the segfault, so may want to update the stable channel to the newer code.

**Comment by kz6fittycent** [comment]
I've moved the latest snap to the `stable` channel. Thanks for your help on this!
