### ISSUE TITLE
Segfaults in GNOME Wayland Environment

### ISSUE THREAD

**Issue by Waddlen** [kz6fittycent/clementine#8]
Hi, thanks for packaging this. However, it crashes on launch in a GNOME Wayland environment, tested on Manjaro and Ubuntu 20.04. This is the output:
```
[waddlen@Laptop ~]$ clementine
17:54:17.523 INFO  main:307                         Clementine-qt5 1.3.1-964-g82b185c08
logging_message17:54:17.523 ERROR unknown                          This application failed to start because it could not find or load the Qt platform plugin "wayland-egl"
logging_message17:54:17.523 ERROR unknown                          in "".
logging_message17:54:17.523 ERROR unknown
logging_message17:54:17.523 ERROR unknown                          Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
logging_message17:54:17.524 ERROR unknown
logging_message17:54:17.524 ERROR unknown                          Reinstalling the application may fix this problem.
Aborted (core dumped)
```

I'm not familiar with packaging applications as Snaps, but I found [this](https://github.com/pbek/QOwnNotes/pull/1012) after a quick search. Thanks!

**Comment by kz6fittycent** [comment]
Thanks for bringing this to my attention. I'm not getting these errors. Do you mind doing a couple of things for me? I've rebuilt it with that package in stage. 

```
sudo snap install --edge clementine

snap run clementine

```

And then posting what you see? If this continues, this is likely an upstream issue with the wayland plug for "all" snaps. I'll have to reach out to them to take a look.

**Comment by Waddlen** [comment]
With the edge version, it now launches on Wayland 🙂 (it already worked fine on X11 for me). Unfortunately it seems like the UI scaling is a little off. Here's what it looks like:
![image](https://user-images.githubusercontent.com/23039119/80068654-fd5cae00-850d-11ea-9ad5-85ce0e3f388a.png)
Packaged version for comparison:
![image](https://user-images.githubusercontent.com/23039119/80068576-d43c1d80-850d-11ea-8a36-3d98ebf3e9a8.png)
Here's the terminal output for the first launch of [snap clementine](https://gist.github.com/Waddlen/40efa1d8846ac57e8166183d6d1a3d3c) and [Manjaro clementine](https://gist.github.com/Waddlen/01955a498342b9ef1d271500d791d50b). 

Not sure if this is the reason, but it stands out to me that the snap tries to use Wayland while the packaged version in Ubuntu and Manjaro use XWayland. Thanks for the quick response and looking into this!

**Comment by kz6fittycent** [comment]
Try refreshing it again, let's see how that works.

**Comment by Waddlen** [comment]
Seems to work great! Now the UI scaling is normal and it respects my Yaru theme; UI looks identical to my second screenshot above. [Here is the output](https://gist.github.com/Waddlen/dbe171147c252ca2732ffb41b786942a) from launching it now.

This is a separate issue, but is it possible for the snap to use the native filepicker? On X11 and Wayland it looks like this:
![image](https://user-images.githubusercontent.com/23039119/80119309-864c0780-8557-11ea-8a59-8beb78462a92.png)
While the packaged version integrates better, using the GNOME filepicker:
![image](https://user-images.githubusercontent.com/23039119/80119360-96fc7d80-8557-11ea-8e2b-85ee930f0b8f.png)

**Comment by kz6fittycent** [comment]
Glad we got it working. As to the file integration, that's part of snap confinement. Most snaps follow this logic, as it's built-in. There's nothing I can do about that as further integration may require `classic` confinement. This snap doesn't qualify. 

You can navigate to your `/home` directory in the file browser, and choose your Music folder for scanning. That's how I'm doing it. 

In any case, I think we can close this particular issue. Any qualms with that?

**Comment by Waddlen** [comment]
Sounds good, thanks for the help.
