### ISSUE TITLE
Main window only shows on 1st. run

### ISSUE THREAD

**Issue by mc4man** [kz6fittycent/clementine#9]
The default setting for When Clementine starts is remember last time which is useless on the snap, at least in Ubuntu.
The effect is the main window only shows on 1st. run, after that only the systray icon which isn't able to open the main window nor preferences..
This affects both the snap and .deb versions in Ubuntu 20.04
https://bugs.launchpad.net/ubuntu/+source/clementine/+bug/1876209

**Comment by kz6fittycent** [comment]
This is an upstream bug. Once upstream provides a fix, we can revisit this. If you're looking to submit a bug to the clementine project, please visit: https://github.com/clementine-player/Clementine
